# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: h2o_ml_agent
# Time Created: 2026-01-11 19:45:57

def h2o_automl(
    data_raw,
    model_directory: str | None = None,
    log_path: str | None = None,
    enable_mlflow: bool = False,
    mlflow_tracking_uri: str | None = None, 
    mlflow_experiment_name: str = "H2O AutoML",
    mlflow_run_name: str | None = None,
    **kwargs
):
    import h2o
    from h2o.automl import H2OAutoML
    import pandas as pd
    import json

    # Optional MLflow usage
    if enable_mlflow:
        import mlflow
        if mlflow_tracking_uri:
            mlflow.set_tracking_uri(mlflow_tracking_uri)
        mlflow.set_experiment(mlflow_experiment_name)
        run_context = mlflow.start_run(run_name=mlflow_run_name)
    else:
        # Dummy context manager to skip MLflow if not enabled
        from contextlib import nullcontext
        run_context = nullcontext()

    # Initialize H2O
    h2o.init()

    # Convert data to H2OFrame
    data_h2o = h2o.H2OFrame(data_raw)

    # Define the target variable
    target = 'y_mfe_log'

    # Determine if target is categorical or numeric
    if len(data_h2o[target].unique()) <= 2:
        data_h2o[target] = data_h2o[target].asfactor()

    # Setup AutoML
    aml = H2OAutoML(
        max_runtime_secs=3600,
        max_models=100,
        seed=1,
        stopping_metric='RMSE',
        **kwargs
    )

    # Train
    aml.train(y=target, training_frame=data_h2o)

    # Save model if we have a directory/log path
    if model_directory is None and log_path is None:
        model_path = None
    else:
        path_to_save = model_directory if model_directory else log_path
        try:
            model_path = h2o.save_model(model=aml.leader, path=path_to_save, force=True)
        except:
            model_path = None

    # Leaderboard (DataFrame -> dict)
    leaderboard_df = aml.leaderboard.as_data_frame()
    leaderboard_dict = leaderboard_df.to_dict()

    # Gather top-model metrics from the first row
    top_metrics = leaderboard_df.iloc[0].to_dict()

    # Construct model_results
    model_results = dict(
        model_flavor="H2O AutoML",
        model_path=model_path,
        best_model_id=aml.leader.model_id,
        metrics=top_metrics
    )

    # IMPORTANT: Log these to MLflow if enabled
    if enable_mlflow and run_context is not None:
        # Log the top metrics if numeric
        numeric_metrics = {k: v for k, v in top_metrics.items() if isinstance(v, (int, float))}
        mlflow.log_metrics(numeric_metrics)

        # Log artifact if we saved the model
        try:
            mlflow.h2o.log_model(aml.leader, name="model")
        except TypeError:
            mlflow.h2o.log_model(aml.leader, artifact_path="model")
        
        # Log the leaderboard
        leaderboard_df = pd.DataFrame(aml.leaderboard)
        leaderboard_dict = leaderboard_df.to_dict()
        mlflow.log_text(json.dumps(leaderboard_dict), "leaderboard.json")

        # Log these parameters (if specified)
        mlflow.log_params(dict(
            target=target,
            max_runtime_secs=3600,
            max_models=100,
            model_directory=model_directory,
            log_path=log_path
        ))

    # Build the output
    output = dict(
        leaderboard=leaderboard_dict,
        best_model_id=aml.leader.model_id,
        model_path=model_path,
        model_results=model_results
    )

    return output