# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: h2o_ml_agent
# Time Created: 2026-01-09 13:16:23

def h2o_automl(
    data_raw,
    model_directory: str = r"c:\Users\Alessandro\Desktop\Cartelle\Mie\Programmi personali in Python\Forecasting BTC with ai-data-science-team\btc_forecast/h2o_models/",
    log_path: str = r"c:\Users\Alessandro\Desktop\Cartelle\Mie\Programmi personali in Python\Forecasting BTC with ai-data-science-team\btc_forecast/ai_logs/",
    enable_mlflow: bool = False,
    mlflow_tracking_uri: str | None = None,
    mlflow_experiment_name: str = "H2O AutoML",
    mlflow_run_name: str | None = None,
    **kwargs
):

    import h2o
    from h2o.automl import H2OAutoML
    import pandas as pd
    import json
    import mlflow
    from contextlib import nullcontext

    # Initialize H2O
    h2o.init()

    # Convert data to H2O Frame, ensure it's not empty and columns are properly defined
    data_raw = pd.DataFrame(data_raw)
    if data_raw.empty:
        raise ValueError("Input data is empty")

    # Ensure all columns are numeric or convert to numeric where possible
    data_raw = data_raw.apply(pd.to_numeric, errors='coerce')
    data_raw.dropna(inplace=True)  # Drop rows with missing values

    # Convert to H2O Frame and specify column data types
    data_h2o = h2o.H2OFrame(data_raw)

    # Setup AutoML
    target = data_raw.columns[-1] # Use the last column as the target
    if target not in data_h2o.columns:
        raise ValueError(f"Target variable '{target}' not found in the data")

    x = [col for col in data_h2o.columns if col != target]

    # Optional MLflow usage
    if enable_mlflow:
        if mlflow_tracking_uri:
            mlflow.set_tracking_uri(mlflow_tracking_uri)
        mlflow.set_experiment(mlflow_experiment_name)
        run_context = mlflow.start_run(run_name=mlflow_run_name)
    else:
        run_context = nullcontext()

    with run_context as run:
        # If using MLflow, track run ID
        run_id = None
        if enable_mlflow and run is not None:
            run_id = run.info.run_id

        aml = H2OAutoML(
            max_runtime_secs=1800,
            max_models=50,
            stopping_metric='rmse',
            exclude_algos=['DeepLearning'],
            seed=1,
            **kwargs
        )

        # Train
        aml.train(y=target, training_frame=data_h2o)

        # Leaderboard (DataFrame -> dict)
        leaderboard_df = aml.leaderboard.as_data_frame()
        leaderboard_dict = leaderboard_df.to_dict(orient='records')

        # Save model if we have a directory/log path
        if model_directory is None and log_path is None:
            model_path = None
        else:
            path_to_save = model_directory if model_directory else log_path
            if aml.leaderboard is not None and len(aml.leaderboard) > 0:
                model_path = h2o.save_model(model=aml.leader, path=path_to_save, force=True)
            else:
                model_path = None

        # Gather top-model metrics from the first row
        if not leaderboard_df.empty:
            top_metrics = leaderboard_df.iloc[0].to_dict()
        else:
            top_metrics = {}

        # Construct model_results
        model_results = dict(
            model_flavor="H2O AutoML",
            model_path=model_path,
            best_model_id=aml.leader.model_id,
            metrics=top_metrics
        )

        # IMPORTANT: Log these to MLflow if enabled
        if enable_mlflow and run is not None:
            # Log the top metrics if numeric
            numeric_metrics = {k: v for k, v in top_metrics.items() if isinstance(v, (int, float))}
            mlflow.log_metrics(numeric_metrics)

            # Log artifact if we saved the model
            try:
                mlflow.h2o.log_model(aml.leader, name="model")
            except TypeError:
                mlflow.h2o.log_model(aml.leader, artifact_path="model")

            # Log the leaderboard
            mlflow.log_json(json.dumps(leaderboard_dict), "leaderboard.json")

        # Build the output
        output = dict(
            leaderboard=leaderboard_dict,
            best_model_id=aml.leader.model_id,
            model_path=model_path,
            model_results=model_results,
            mlflow_run_id=run_id
        )

    return output